apiVersion : apps/v1
kind: Deployment
metadata:
  name: "gatewaybvtsaks2-3e89"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gatewaybvtsaks2-3e89"
  template:
    metadata:
      labels:
        app: "gatewaybvtsaks2-3e89"
    spec:
      containers:
        - name: "gatewaybvtsaks2-3e89"
          image: "websocketecho.azurecr.io/gatewaybvtsaks2"
          ports:
          - containerPort: 8010